<!-- 
    Feeds
-->

<div id="SocialNetworkFeed">

<!--
Twitter
-->

<!--
<a class="twitter-timeline" data-width="250" data-height="800" data-theme="light" 
  href="https://twitter.com/C_Andreopoulos?ref_src=twsrc%5Etfw">
  Tweets by C_Andreopoulos</a> 
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

<br />
<br />
-->

<!--
IG
-->

<A href="https://www.instagram.com/livunineutrino" target="_top">
  <img src="./images/icons/instagram_01.png" valign="top" width="20px" height="20px" alt="Group Instagram account">
  Group Instagram account feed</A>

<br />
<br />

<!-- Place <div> tag where you want the feed to appear -->
<div id="curator-feed-default-feed-layout"><a href="https://curator.io" target="_blank" class="crt-logo crt-tag">Powered by Curator.io</a></div><!-- The Javascript can be moved to the end of the html page before the 
</body> tag --><script type="text/javascript">
/* curator-feed-default-feed-layout */
(function(){
var i,e,d=document,s="script";i=d.createElement("script");i.async=1;i.charset="UTF-8";
i.src="https://cdn.curator.io/published/fa84d282-3dc5-4442-a3c5-829b83c1ec54.js";
e=d.getElementsByTagName(s)[0];e.parentNode.insertBefore(i, e);
})();
</script>

</div>

