  <head>
     <link type="text/css" rel="stylesheet" href="./css/costas_style.css" />
     <title>
       Costas Andreopoulos, 
       Neutrino Physicist and Professor of Experimental Particle Physics at the University of Liverpool.
     </title>
<!-- 
    <meta name="viewport" content="width=device-width, initial-scale=1">
-->
     <meta name="description" content=
          "Prof. Costas Andreopoulos's (University of Liverpool) home page.">
     <meta http-equiv="Keywords" content=
         "costas.andreopoulos.eu, Costas, Constantinos, Andreopoulos, 
          High Energy Physics, HEP, Particle Physics, Neutrino, 
          Quantum Computing, Quantum Error Correction, Quantum Machine Learning,
          Machine Learning, Deep Learning, Neural Networks,
          COSMOS, DONUT, MINOS, SK, Superk-Kamiokande, ND280, T2K, T2HK, DUNE, LBNE, LBNF, SBN, SBND, FERMILAB, J-PARC, NUMI, BOOSTER, JUNO,
          PPD, University of Liverpool, Liverpool, SciTech, STFC, Rutherford, Rutherford Appleton Lab, RAL, Athens, Greece, Oxford, UK,
          Neutrino Oscillations, CPV, CP violation, Mass Ordering, BSM,
          Neutrino Interactions, Cross Sections, Hadronization, Hadron Transport, Phenomenology, AGKY,
          Heavy Neutral Leptons, Dark Neutrinos, Dipole Portal, Axion Portal,
          VALOR, VALOR-SDK, GENIE, Event Generator, Monte Carlo, MC, Global Fit, Global Analysis">
  </head>

  <!--
        Header
   -->

   <div id="Header">
       Professor Costas Andreopoulos<i style="font-size:17px">, FHEA</i>
      <IMG src="./images/logo/liverpool_3.png" valign="top" align="right"  height="44px">
   </div>

