  <head>
     <link type="text/css" rel="stylesheet" href="./css/costas_style.css" />
     <title>
        Prof. Costas Andreopoulos, Neutrino Physicist at the University of Liverpool and STFC Rutherford Appleton Laboratory
     </title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content=
          "Prof. Costas Andreopoulos's (University of Liverpool and STFC Rutherford Appleton Laboratory) home page.
           Links to work on T2K neutrino oscillation physics analysis, GENIE / neutrino interaction phenomenology
           and R&D towards future neutrino experiments">
     <meta http-equiv="Keywords" content=
         "costas.andreopoulos.eu, Costas, Constantinos, Andreopoulos, 
          High Energy Physics, HEP, Particle Physics, Neutrino, 
          COSMOS, DONUT, MINOS, SK, Superk-Kamiokande, ND280, T2K, T2HK, DUNE, LBNE, LBNF, SBND, FERMILAB, J-PARC, NUMI, BOOSTER,
          PPD, University of Liverpool, Liverpool, SciTech, STFC, Rutherford, Rutherford Appleton Lab, RAL, Athens, Greece, Oxford, UK,
          Neutrino Oscillations, 
          Neutrino Interactions, Cross Sections, Hadronization, Hadron Transport, Phenomenology, GENIE, Neutrino MC Generator, Monte Carlo">
  </head>

  <!--
        Header
   -->

   <div id="Header">
       Professor Costas Andreopoulos<i style="font-size:17px">, FHEA</i>
<!--
      <IMG src="./images/logo/ral.jpg" valign="top" align="right" height="35px">
-->
      <IMG src="./images/logo/liverpool.png" valign="top" align="right"  height="44px">
   </div>

