    <!-- 
        Navigation bar 
    -->

    <div id="NavBar">
      <center>
        <A href="./index.html">        
          Home</A>      
        <A href="./news.html">         
          News</A>
        <A href="./research.html">     
          Research</A>
        <A href="./teaching.html">     
          Teaching</A>
        <A href="./phd_students.html"> 
          PhDs</A>
        <A href="./group.html">        
          Group</A>
        <A href="./roles.html">        
          Roles</A>
        <A href="./publications.html"> 
          Publications</A>
        <A href="./talks.html">        
          Presentations</A>
        <A href="https://doodle.com/mm/costasandreopoulos/book-a-time" target="_top">     
          Calendar</A>
        <A href="./contact.html">      
          Contact</A>
      </center>
    </div>

