    <!-- 
       Twitter stream 
    -->

    <div id="TwitterFeed">

        <a class="twitter-timeline" data-width="250" data-height="500" data-theme="light" 
           href="https://twitter.com/C_Andreopoulos?ref_src=twsrc%5Etfw">
            Tweets by C_Andreopoulos</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
        <br />
        <br />
    </div>

